fix compile error in cgroup_taskset_for_each() when skip_css is NULL
The gcc error message is:
include/linux/cgroup.h:587:14: error: request for member ‘ss’ in something
not a structure or union

Signed-off-by: Dwight Engen <dwight.engen@oracle.com>